#!/bin/bash
#SBATCH --partition=OBS
#SBATCH --job-name=org
#SBATCH --time=48:00:00
#SBATCH --nodes=10
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=mqezlou@carnegiescience.edu
#SBATCH --mem=MaxMemPerNode


module load gnu7
#module load gsl
module load mpich
mpirun python run_organize_prog_map.py


