#!/bin/bash

#SBATCH --job-name=2.4,root
#SBATCH --time=0:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --cpus-per-task=1
#SBATCH --mem=MaxMemPerNode

module load gnu7
module load gsl
module load mpich
mpirun python3 run_find_roots.py



