#!/bin/bash

#SBATCH --job-name=DnMD
#SBATCH --time=02:00:00
#SBATCH --nodes=3
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=2
#SBATCH --mem=160G
export OMP_NUM_THREADS=2
module load gsl/2.4
module load mpich/4.0.0

mpirun python3.6 run_density.py --snaps '/central/scratch/mqezlou/MDPL2/output/snapdir_073/hdf5/snap_073.*.hdf5' --savedir './results/' --savefile='./MDPL2_density_pnbodypy.hdf5' --Nmesh 1000 --simtype 'Converted_Gadget_old' --boxsize 1000000





