#!/bin/bash

#SBATCH --partition=OBS
#SBATCH --job-name=DenT300
#SBATCH --time=02:00:00
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=6
#SBATCH --mem=MaxMemPerNode
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

#export I_MPI_FABRICS=shm
module load gnu7
module load gsl
module load mpich

mpirun python3.6 run_density.py --snaps '/lustre/scratch/mqezlou/TNG300-1/output/snapdir_029/snap_029.*' --savedir './results/' --savefile='./TNG_DM_z2.4_fixed.hdf5' --Nmesh=205





