#!/bin/bash

#SBATCH --partition=SHARED
#SBATCH --job-name=Dens100
#SBATCH --time=02:00:00
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=6
#SBATCH --mem=MaxMemPerNode
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

#export I_MPI_FABRICS=shm
module load gnu7
module load gsl
module load mpich

mpirun python3.6 run_get_densityfield.py --snaps '/lustre/scratch/mqezlou/TNG100-1/output/DM_only/snapdir_028/snap_028.*' --savedir './results/' --Nmesh=75





