#!/bin/bash

#SBATCH --partition=OBS
#SBATCH --job-name=FgRob
#SBATCH --time=02:00:00
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=6
#SBATCH --mem=MaxMemPerNode
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

#export I_MPI_FABRICS=shm
module load gnu7
module load gsl
module load mpich

#mpirun python3.6 run_FGPA.py --func 'density' --snaps '/lustre/scratch/mqezlou/TNG100-1/output/DM_only/snapdir_033/snap_033.*' --savedir './density_real/' --Nmesh 1800
mpirun python3.6 run_FGPA.py --func 'map' --z 2.0020281392528516 --savedir './density_real/' --savefile './FGPA_TNG100_z2.0_0.25Mpc_ourFGPA.hdf5' --boxsize 75 --Ngrids 300 --Npix 300





